//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theEducators.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Article
    {
        public Article()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public bool IsClientArticle { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        public string CreatedByName { get; set; }
        public string LastEditedByName { get; set; }
        public int CreatedByID { get; set; }
        public int LastEditedByID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastEditedOn { get; set; }
        public string Tag { get; set; }
        public int UserId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
